# Site
repository: knight2995/resume
favicon: images/favicon.ico

# Personal info
name: 김동현
title: Newbie Developer
email: knight2995@kakao.com
website: https://knight2995.github.io

# Social links
twitter_username: 
github_username:  knight2995
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: duckbojjang
linkedin_username: 
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 김동현입니다.
  현재 전문연구요원 신입으로 직장을 구하고 있습니다.
  학교 연구실에서 이미지 프로세싱과 딥러닝을 이용한 많은 연구과제를 수행하였습니다.
  <mark>어제보다 조금 더 나은 사람이 되자</mark>를 모토로 삼고 있습니다.

# Skills Section
# skills_title: Skills

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  저는 개발외에 아래에 관심이 있습니다 :
   - Weight Trainning
   - Weight Lifting

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-theme
#theme: resume

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

baseurl: /resume
url: knight2995.github.io
